### ISSUE TITLE
Use rack-flash with sinatra test environment

### ISSUE THREAD

**Issue by 9z0b3t1c** [nakajima/rack-flash#1]
I'm developing a Sinatra application using cucumber.

In my env.rb cucumber configuration file, I have specified:

set :environment, :test

This gives me an error:

Rack::Flash::SessionUnavailable - Rack::Flash depends on session middleware

If you could tell me what's causing that, or how to get round it - would be much appreciated.

Am using:
cucumber (0.4.4)
rack (1.0.1)
rack-flash (0.1.1)
rack-test (0.5.3)
sinatra (0.9.4)

Thanks,
Steven

**Comment by nakajima** [comment]
Yea, this is sort of a pain with testing sessions. You can `require "rack/flash/test"` in your test helper and it should fake the session for you. Let me know if that doesn't work.

**Comment by 9z0b3t1c** [comment]
That worked --- thanks very much :)

**Comment by benschwarz** [comment]
Please add this to your README, cause it caught me out for half an hour.. you might save your users some time :)
